### ISSUE TITLE
Feature Request : Allow name prefix on created resources

### ISSUE THREAD

**Issue by peterver** [digitalocean/digitalocean-cloud-controller-manager#102] opened 2018-05-17 12:55 UTC
At the moment when for example a load balancer is provisioned through CCM it gets assigned a name that is bound to be unique.

This approach works beautifully for a purely machine-based operator. But since there is no way to prefix a resource name it leads to confusion when looking at the digitalocean dashboard. As such it would/could be beneficial to allow for a prefix to be set ( a prefix, not an override ).

For example : let's say a load balancer in the current scheme would get a uid of qwerty123
with a prefix it could become something like : staging-api-qwerty123

Which is both unique for automation reasons and allows for readability to human operators

This behavior can be added through an annotation, or could take the name of the k8s service managing it as the prefix.

In regards to verification it would need to take into account any limitations digitalocean poses on the length of the name that a resource such as a loadbalancer can have

**Comment by andrewsykim** [comment] 2018-05-17 13:38
Prefixing will be tricky because we actually rely on the service controller from upstream Kubernetes to handle this part for us. We could add a prefix to whatever name is generated by Kubernetes but that could lead to unexpected behaviour from the service controller.  Might be better to add that logic to the [Kubernetes service controller](https://github.com/kubernetes/kubernetes/tree/master/pkg/controller/service) instead of trying to patch it here. What do you think?

**Comment by andrewsykim** [comment] 2018-05-17 14:30
Yeah, unfortunately `cloudprovider.GetLoadBalancerName` is a shared method and not something that can be overwritten by each cloud provider (yet). As mentioned in the issue, changing something like the loadbalancer name requires very careful consideration since you don't want to break code paths that need to know about the previous LB names.  

Having said that, it's not impossible to override LB names that are passed in from the service controller, but it may lead to unexpected behaviours in the future since service controller may have assumptions about the LB name. I think annotations to override this would be okay as long as users are aware of the implications 😬.

**Comment by lxfontes** [comment] 2018-09-10 21:57
feels like what we really want here is LB tags ;)

**Comment by andrewsykim** [comment] 2018-09-13 17:53
+1 for tags, upstream recently merged https://github.com/kubernetes/kubernetes/pull/66589 as well so starting in v1.12 we have to implement our own GetLoadBalancerName method (optional fallback to current naming format). Only tricky bit here is accounting for existing LBs with the old name.

**Comment by peterver** [comment] 2018-09-19 11:41
+1 :) would love to see lb tags :D, for me the whole point is to be able to organize resources. Whether that is through tags or naming doesn't matter. As long as it's possible :) 

Thanks for replying @lxfontes @andrewsykim

**Comment by timoreimann** [comment] 2019-02-26 00:04
The upcoming v0.1.9 release of CCM will tag LB resources with the cluster ID. See the [documentation](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/f112671a5bc83492cc975b702edf7fa5c6181587/docs/getting-started.md#resource-tagging) as well as the associated PRs #170, #178, and #181.

@peterver would that fit your use case?

**Comment by timoreimann** [comment] 2019-10-08 15:29
LBs can now be renamed manually for low-volume cases. Please reopen a new ticket if naming through annotations is desired.

**Closed by timoreimann** 2019-10-08 15:29 UTC
