### ISSUE TITLE
Preserve client IP address on both HTTP and HTTPS

### ISSUE THREAD

**Issue by joshrendek** [digitalocean/digitalocean-cloud-controller-manager#144] opened 2018-11-05 01:53 UTC
On other cloud providers you would generally set `externalTrafficPolicy: Local` to preserve the IP information being passed along from the LB. Currently DO's load balancers do not do this / support this.

Example:

`curl https://ifcfg.net` returns `10.136.140.29`

Headers from the backend:

```
map[Accept:[*/*] X-Forwarded-Port:[80] X-Forwarded-Server:[traefik-6f7469496d-xwqlk] Accept-Encoding:[gzip] User-Agent:[curl/7.54.0] X-Forwarded-For:[10.136.140.29] X-Forwarded-Host:[ifcfg.net] X-Forwarded-Proto:[http] X-Real-Ip:[10.136.140.29]]
```

However if I query the nodePort directly for Traefik: 

```
curl -H "Host: ifcfg.net" 68.183.30.xxx:31978
47.201.184.xx
```

Headers from the backend:

```
map[User-Agent:[curl/7.54.0] Accept:[*/*] X-Forwarded-Proto:[http] X-Real-Ip:[47.201.184.xx] X-Forwarded-Server:[traefik-6f7469496d-xwqlk] Accept-Encoding:[gzip] X-Forwarded-For:[47.201.184.xx] X-Forwarded-Host:[ifcfg.net] X-Forwarded-Port:[80]]
```

I get the right response back.

Outstanding issues:

* https://www.digitalocean.com/community/questions/load-balancer-does-not-forward-source-ip
* https://www.digitalocean.com/community/questions/transparent-load-balancers
* https://www.digitalocean.com/community/questions/get-client-source-ip-with-kubernetes-load-balancer-service

**Comment by andrewsykim** [comment] 2018-11-05 14:43
@joshrendek what is the protocol set on your LB?

**Comment by joshrendek** [comment] 2018-11-05 15:07
@andrewsykim it was the defaults that come up (afaik it was TCP) when setting traefik to class `LoadBalancer` instead of `NodePort`.

**Comment by andrewsykim** [comment] 2018-11-05 15:20
@joshrendek you probably want to set the LB protocol to `http`, otherwise it will not do any header modifications (see [here](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/docs/controllers/services/examples/http-nginx.yml#L7) for example).

**Comment by joshrendek** [comment] 2018-11-05 16:10
@andrewsykim how would that work for SSL if I want the termination to happen at traefik? 

I can get the correct behavior with HAProxy using the `send-proxy` directive on the backends

**Comment by andrewsykim** [comment] 2018-11-05 16:14
You can specify TLS ports with annotations as well, here's an example that does TLS termination https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/docs/controllers/services/examples/https-with-cert-nginx.yml#L9

**Comment by joshrendek** [comment] 2018-11-05 16:19
@andrewsykim sorry not sure I was clear - i don't want the LB to do termination since its using LetsEncrypt and has a bunch of different domains behind it, i want traefik to do that and really just have the LB pass through like haproxy is

**Comment by andrewsykim** [comment] 2018-11-05 16:23
I see, so seems like you want to still specify TLS ports and configure TLS pass through like [this](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/docs/controllers/services/examples/https-with-pass-through-nginx.yml#L9). That should pass through all traffic via TLS and let traefik handle any application level routing. Let me know if that's what you were looking for :)

**Comment by joshrendek** [comment] 2018-11-05 16:49
@andrewsykim awesome i'll give that whirl later today - and at the very least if it doesn't work, give full reproduction steps with a fresh cluster

**Comment by joshrendek** [comment] 2018-11-06 02:12
@andrewsykim this only partially works 

So if I setup a load balancer as `HTTP -> HTTP` I get the `X-Forwarded-For` header set and get a response like:

`47.201.184.xx, 10.244.97.0` - which would be okay

If I setup HTTPS as pass through however, I get:

`10.244.25.1`

For context the ruleset is:

![image](https://user-images.githubusercontent.com/36339/48038628-73fdc400-e13f-11e8-94b3-248223d1ce82.png)

Similarly if I just do `TCP` -> `TCP` I get a internal network IP as well: `10.244.25.1`

The HAProxy config still works like I'd expect it to (however I lose the ability to use a DO LB and the redundancy that comes with that)

**Comment by andrewsykim** [comment] 2018-12-05 16:59
Sorry for the late reply here. I'm not sure if `X-Forwarded-For` headers will work over HTTPS cause the load balancer cannot modify/see the http headers.

**Comment by aurokk** [comment] 2019-01-03 22:56
@andrewsykim 
Hello, is there some news? :)

**Comment by andrewsykim** [comment] 2019-01-04 07:59
IIRC that is correct. You won't be able to see `X-Forwarded-For` headers when doing HTTPS -> HTTPS.

**Comment by aurokk** [comment] 2019-01-04 21:59
Ok. 

I think i can use K8S ingress and my requests are being processed this way: 
client -> K8S ingress (tls termination) -> K8S svc -> pod

But in fact i have:
client -> LB -> K8S ingress (tls termination) -> K8S svc -> pod

I thought LB and K8S — one entity :)

So...
**What is the right way to use DO K8S + LB?**

**Should i create a DO LB for each K8S-service?** 
(without ingress, scheme: client -> LB (tls termination) -> K8S svc -> pod)

**Isn't [NGINX proxy protocol](https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/) resolves this problem?**

**Comment by aurokk** [comment] 2019-01-07 13:47
I asked support about proxy protocol and they answered: 

```
Sorry to hear that you are experiencing issues with this. At this time, Proxy protocol is not supported on our Load Balancers and this is why the client IP is not being forwarded. Our engineering team that manages the Load Balancers service is aware of this limitation and is currently working toward a solution, however it is not clear how long that will take. In the meantime, it would not be possible to change the relationship from our Kubernetes Service to our Load Balancers managed on our platform. We hope to be able to offer a solution to this soon. Sorry for the inconvenience.
```

I think we should wait for proxy protocol on LB :)

**Comment by timoreimann** [comment] 2019-02-24 08:02
Let's keep this issue open until client IP addresses can be properly transmitted through TLS connections to LoadBalancer-typed services. Depending on the chosen implementation, this may or may not need a change to CCM once a solution has been found on the DO LB end.

**Comment by Berndinox** [comment] 2019-02-24 10:03
+1

**Comment by gboor** [comment] 2019-03-01 20:59
I also really need this to work. I have a domain running through Cloudflare, so I cannot move the DNS to DigitalOcean easily - which seems to be required to do TLS termination on the DO LB.

Can we get any sort of timeline for this?

**Comment by daanwa** [comment] 2019-03-09 09:30
Facing the same problem. Would really like to get this to work.

**Comment by lpellegr** [comment] 2019-03-09 09:32
I discussed with the support recently about this issue for a similar need. It seems Digital Ocean team is working on a solution for the end of this month.

**Comment by thedumbtechguy** [comment] 2019-03-17 06:10
Same here. Supporting Proxy Protocol for TCP should be a good start as it will solve 90% of people's problems.

**Comment by lpellegr** [comment] 2019-03-19 21:10
@timoreimann Just noticed Proxy Protocol is now available with Digital Ocean load balancers. 

I just made a try by creating a fresh cluster and deployment pods, ingress, etc. as explained on the next and great Digital Ocean tutorial:

https://www.digitalocean.com/community/tutorials/how-to-set-up-an-nginx-ingress-with-cert-manager-on-digitalocean-kubernetes

Then, I have manually enabled Proxy Protocol from the DO dashboard for the new load balancer.

My services and pods are running properly if I check the status and even their logs. However, when I try to perform an HTTP GET to a REST endpoint, the only response I get is a 400 Bad Request from Nginx. I guess it is related to the load balancer. 

Is there any documentation that explains how to configure Proxy Protocol with Kubernetes?

**Comment by timoreimann** [comment] 2019-03-19 22:41
Hi @lpellegr 

yes, we released support for PROXY protocol earlier today 🎉. Our [official blog post](https://blog.digitalocean.com/load-balancers-now-support-proxy-protocol/) has more information and [points](https://www.digitalocean.com/docs/kubernetes/how-to/configure-load-balancers/#proxy-protocol) at the service annotation you should use, which is

```
service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
```

Adding that to your Service object should do the trick. An full example is available [here](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/68f5e06565659dcd45c3c608dd05d542ad111e66/docs/controllers/services/examples/http-nginx-with-proxy-protocol.yml#L7).

Please note that older clusters need to have their master nodes recycled, which is something our support team can do for you. Newly created clusters will come with PROXY protocol support right away.

Hope this helps!

**Comment by timoreimann** [comment] 2019-03-19 22:44
Closing this issue as the feature has been implemented along #198.

Please open a new issue if you run into problems, thanks.

**Closed by timoreimann** 2019-03-19 22:44 UTC

**Comment by ptariche** [comment] 2019-03-19 23:11
https://blog.digitalocean.com/load-balancers-now-support-proxy-protocol/?utm_source=local&utm_medium=Email&utm_campaign=LBProxyProtocolRelease 👏  👏

**Comment by ptariche** [comment] 2019-03-20 02:08
I can confirm the Proxy Protocol implementation also works with Traefik.

```
        - --api
        - --kubernetes
        - --logLevel=INFO
        - --ping
        - --ping.entrypoint=hc
        - --defaultentrypoints=http
        - --entryPoints=Name:https Address::443 TLS Compress:true ProxyProtocol.Default:true ProxyProtocol.TrustedIPs:10.0.0.0/8,127.0.0.1,::1,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,104.16.0.0/12,108.162.192.0/18,131.0.72.0/22,141.101.64.0/18,162.158.0.0/15,172.64.0.0/13,173.245.48.0/20,188.114.96.0/20,190.93.240.0/20,197.234.240.0/22,198.41.128.0/17,2400:cb00::/32,2405:b500::/32,2606:4700::/32,2803:f800::/32,2c0f:f248::/32,2a06:98c0::/29
        - --entryPoints=Name:http Address::80 Compress:true ProxyProtocol.Default:true ProxyProtocol.TrustedIPs:(CIDR)
        - --entryPoints=Name:hc Address::8000 Compress:true
        - --defaultentrypoints=http
        - --sendanonymoususage=false
```

**Comment by ptariche** [comment] 2019-03-20 02:09
I can confirm the Proxy Protocol implementation also works with Traefik.

```
        - --api
        - --kubernetes
        - --logLevel=INFO
        - --ping
        - --ping.entrypoint=hc
        - --defaultentrypoints=http
        - --entryPoints=Name:https Address::443 TLS Compress:true ProxyProtocol.Default:true ProxyProtocol.TrustedIPs:(CIDR)
        - --entryPoints=Name:http Address::80 Compress:true ProxyProtocol.Default:true ProxyProtocol.TrustedIPs:(CIDR)
        - --entryPoints=Name:hc Address::8000 Compress:true
        - --defaultentrypoints=http
        - --sendanonymoususage=false
```

**Comment by thedumbtechguy** [comment] 2019-04-10 12:13
I can also confirm that it works with Kong.

**Comment by snuxoll** [comment] 2019-04-19 21:31
Unfortunately the PROXY protocol support of the DigitalOcean load balancers does not properly work with cert-manager either, I've opened support ticket 02611202 with DigitalOcean for myself but I'll post here as well.

It appears DO's load balancers are configured with a hairpin NAT or similar configuration, if you try to access them from a droplet that is backed by them you will have your traffic routed straight back instead of proxied via the load balancer. This prevents cert-manager from running checks about the availability of ACME challenges, since configuring an ingress controller to accept PROXY protocol traffic prevents it from accepting normal HTTP(S) requests - and since these requests aren't ACTUALLY going through the LB they fail.

You can test this without even using k8s, throw up a LB in front of a droplet running nginx with the proxy protocol configured and try to curl http://my.lb.ip.addr/ from said droplet - the connection will drop.

**Comment by jcassee** [comment] 2019-04-19 21:41
@snuxoll I think you are running into #193

**Comment by snuxoll** [comment] 2019-04-19 22:09
@jcassee Similar issue, but I am not using HTTP/HTTPS termination at the load balancer - it is running in pure TCP mode.

**Comment by jcassee** [comment] 2019-04-20 07:57
@snuxoll Yeah, I meant it's the same core issue (kubernetes/kubernetes#66607), but I see you already found it.

**Comment by michiels** [comment] 2019-06-07 21:34
@timoreimann @ptariche 

Hi both. Thank you for the PROXY support and your Traefik startup arguments. I've tested the setup and it does indeed work that PROXY support now passes on the source IP to a Traefik ingress controller service in the Kubernetes cluster.

I have one problem however: which CIDR should we enter to trust? If I enter just the public IP of the DO LB, it does not forward the source IP to the backend apps. However, if I add the "ProxyProtocol.Insecure = true" flag it *does* work.

If I look at my traffic logs, I do see an internal `10.x.x.x` IP address as incoming source to the backend service. However, this does not look like one of the IPs of my nodes. Can I assume this is the internal source IP of the DigitalOcean Load balancer that we need to put in the Traefik startup arguments? Or will this IP address change over time due to DOs internal routing or Kubernetes network setup?

**Comment by ptariche** [comment] 2019-06-07 21:53
@michiels  Traefik startup arguments as trusted IP need to be the ip ranges of the source. So, if you're using cloudflare. You'd want to add those. https://www.cloudflare.com/ips-v4

**Comment by michiels** [comment] 2019-06-07 22:13
@ptariche Thanks. I'm not using CloudFlare but I'm using a DigitalOcean Load Balancer as the Traefik deployment is set up as a Kubernetes Service with type=LoadBalancer. The DO LB IP goes into our DNS records directly.

**Comment by KadenLNelson** [comment] 2019-06-08 14:19
> @ptariche Thanks. I'm not using CloudFlare but I'm using a DigitalOcean Load Balancer as the Traefik deployment is set up as a Kubernetes Service with type=LoadBalancer. The DO LB IP goes into our DNS records directly.

I'm running into the same problem specifying the LoadBalancer as a trustedIP for ProxyProtocol. I think we need the internal/private IP of the load balancer to accomplish this, but it doesn't seem that DigitalOcean provides this for us.

**Comment by ptariche** [comment] 2019-06-09 17:15
For the DO LB you don’t know the external IP until after it’s been created so it maybe something you have to do retroactively.

**Comment by timoreimann** [comment] 2019-06-09 17:42
@michiels that 10.x.x.x IP address you're seeing should be the internal one of the proxy, correct. Unfortunately, it cannot be relied upon to be stable -- even if it looks stable-ish now, there are conditions under which it may change, even across two consecutive requests.

Do I understand correctly that the use case here is to prevent client IP address forgery by relying on the fronting DO LB to do the proper validation? If so, I wonder if a different avenue to tackle the problem might be to firewall off access to the NodePorts from all clients except for the LB. I'd have to double-check, but I believe the existing tagging infrastructure would allow for this kind of filtering already. (In fact, #70 may already go in this direction, the PR lost traction at some point.)

Any thoughts on this idea?

**Comment by michiels** [comment] 2019-06-11 14:16
@timoreimann Right. I already assumed that the internal IP of the LB might change depending on the dynamics for your DO LB internal infrastructure.

It is indeed to prevent client IP address forgery. Only trusted proxies/LBs may forward a trusted client IP to our backend services. Traefik, the ingress router that we use, has been configured to only trust the LB IP for the PROXY protocol (or accepting X-Forwarded-For headers).

If I understand correctly the alternative route you suggest, I think it would indeed be a good alternative to only allow the LB to forward traffic into the cluster by fully disabling external access on the NodePorts of the public IPs of the individual droplets in the cluster. In fact, ideally, I wouldn't want to expose any public IPs or ports of the individual machines in the cluster to the public internet. This is how for example Azure K8s Cluster approaches it too. This way you know all traffic coming into the exposed NodePorts can only come from the LB. Of course, I realize that some users would actually like to expose individual services in their cluster to the outside world. But in the case that you put an LB in front of it, I can't come up with a reason to expose individual nodes to the public internet.

I'll have a look at #70 if that matches my problem or a solution. I'm not a cloud infrastructure developer myself however :)
