### ISSUE TITLE
Inconsistencies with https and healthcheck service loadbalancer annotations

### ISSUE THREAD

**Issue by malkir** [digitalocean/digitalocean-cloud-controller-manager#158] opened 2018-12-18 09:57 UTC
I'm seeing inconsistent behavior when using service loadbalancer annotations.

The goal: 
Create a service type load balancer, using https, and a tcp healthcheck.

The issue: 
In order for `service.beta.kubernetes.io/do-loadbalancer-certificate-id` and `service.beta.kubernetes.io/do-loadbalancer-tls-ports` to be honored, `service.beta.kubernetes.io/do-loadbalancer-protocol: "http"` must be present. However ``service.beta.kubernetes.io/do-loadbalancer-protocol: "http"`` does not work with `service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "tcp"`, despite documentation stating otherwise.

Reproduce:

I've created 5 manifests pointing to an nginx deployment, 80->80 and 443->80. I've generated a letsencrypt cert from within DO's loadbalancer manually. The only difference between my 5 manifests are the annotations, and I've created a fresh load balancer for each of the 5 manifests.

1) Note the healthcheck is correctly set to TCP:

```
service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "tcp"
```

```
22ea2d32-784c-4a9b-8c59-b380cec23b44    104.248.109.58    ac37769a302a711e988b706264698a7d    active    2018-12-18T09:31:58Z    round_robin    nyc1             123329176,123329177,123329178    false    type:none,cookie_name:,cookie_ttl_seconds:0    protocol:tcp,port:30660,path:,check_interval_seconds:3,response_timeout_seconds:5,healthy_threshold:5,unhealthy_threshold:3    entry_protocol:tcp,entry_port:443,target_protocol:tcp,target_port:30660,certificate_id:,tls_passthrough:false entry_protocol:tcp,entry_port:80,target_protocol:tcp,target_port:31062,certificate_id:,tls_passthrough:false entry_protocol:tcp,entry_port:8080,target_protocol:tcp,target_port:30124,certificate_id:,tls_passthrough:false
```

2) Added the `do-loablanacer-protocol`, the tcp healthcheck no longer works, it's back to http:
```
service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "tcp"
service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
```

```
e9cf7dd9-d5f7-43ad-89c3-43f864ba1d8b          ae974cee802a911e988b706264698a7d    new       2018-12-18T09:47:21Z    round_robin    nyc1             123329176,123329177,123329178    false    type:none,cookie_name:,cookie_ttl_seconds:0    protocol:http,port:31355,path:/,check_interval_seconds:3,response_timeout_seconds:5,healthy_threshold:5,unhealthy_threshold:3    entry_protocol:http,entry_port:443,target_protocol:http,target_port:31355,certificate_id:,tls_passthrough:false entry_protocol:http,entry_port:80,target_protocol:http,target_port:32413,certificate_id:,tls_passthrough:false entry_protocol:http,entry_port:8080,target_protocol:http,target_port:32543,certificate_id:,tls_passthrough:false
```

3) Set HTTPS only, no `do-loadbalancer-protocol`, certificate not set and https not selected, but TCP healthcheck selected???
```
service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
service.beta.kubernetes.io/do-loadbalancer-certificate-id: "MY_CERT_ID"
```

```
59ec111e-2adf-4633-acb4-7ee545bb201a                      a1e8b990502a811e988b706264698a7d    new       2018-12-18T09:34:31Z    round_robin    nyc1             123329176,123329177,123329178    false    type:none,cookie_name:,cookie_ttl_seconds:0    protocol:tcp,port:30170,path:,check_interval_seconds:3,response_timeout_seconds:5,healthy_threshold:5,unhealthy_threshold:3    entry_protocol:tcp,entry_port:443,target_protocol:tcp,target_port:30170,certificate_id:,tls_passthrough:false entry_protocol:tcp,entry_port:80,target_protocol:tcp,target_port:31404,certificate_id:,tls_passthrough:false entry_protocol:tcp,entry_port:8080,target_protocol:tcp,target_port:32579,certificate_id:,tls_passthrough:false
```

4) Set SSL definitions, this time with `do-loadbalancer-protocol`, SSL works, back to HTTP healthcheck:

```
service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
service.beta.kubernetes.io/do-loadbalancer-certificate-id: "MY_CERT_ID"
```

```
88eac3ad-956b-4cda-9a59-b5cf284d55f2                      a7fc049d602a811e988b706264698a7d    new       2018-12-18T09:37:18Z    round_robin    nyc1             123329176,123329177,123329178    false    type:none,cookie_name:,cookie_ttl_seconds:0    protocol:http,port:31599,path:/,check_interval_seconds:3,response_timeout_seconds:5,healthy_threshold:5,unhealthy_threshold:3    entry_protocol:http,entry_port:80,target_protocol:http,target_port:31815,certificate_id:,tls_passthrough:false entry_protocol:https,entry_port:443,target_protocol:http,target_port:31599,certificate_id:MY_CERT_ID,tls_passthrough:false entry_protocol:http,entry_port:8080,target_protocol:http,target_port:31766,certificate_id:,tls_passthrough:false
```

5) Set SSL, do-loadbalancer-protocol, and tcp healthcheck... SSL cert is not set, HTTPS is not set, and TCP healthcheck is not set: 

```
service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
service.beta.kubernetes.io/do-loadbalancer-certificate-id: "MY_CERT_ID"
service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "tcp"
```

```
219106e0-7332-49d5-94b2-947bab719695                      aa8a6622002a811e988b706264698a7d    new       2018-12-18T09:38:24Z    round_robin    nyc1             123329176,123329177,123329178    false    type:none,cookie_name:,cookie_ttl_seconds:0    protocol:http,port:32572,path:/,check_interval_seconds:3,response_timeout_seconds:5,healthy_threshold:5,unhealthy_threshold:3    entry_protocol:http,entry_port:80,target_protocol:http,target_port:30592,certificate_id:,tls_passthrough:false entry_protocol:https,entry_port:443,target_protocol:http,target_port:32572,certificate_id:79944daa-11e4-4b86-a7d3-d4628b7f98f9,tls_passthrough:false entry_protocol:http,entry_port:8080,target_protocol:http,target_port:32271,certificate_id:,tls_passthrough:false
```

Tis broke
¯\\_(ツ)_/¯

Let me know and I can provide complete manifests if you'd like to do more testing.

**Comment by timoreimann** [comment] 2019-01-06 00:11
I can reproduce the problem with step no. 2 already. Looking at the code, I don't see an immediate reason for the behavior, but I'll try to dig deeper.

**Comment by timoreimann** [comment] 2019-01-06 00:55
Turned out the reason why step no. 2 failed is very simple: The `service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol` annotation has just not been released yet: #147 was merged in November only.

The other behaviors may or may not follow up from that; I'm running out of time today but will check soon.

**Comment by timoreimann** [comment] 2019-01-06 01:15
So in CCM v0.1.8, the health check protocol always matches the load-balancer protocol (which defaults to TCP unless overridden via an annotation). It's basically the same in master (aka the future v0.1.9) except for the fact that the health check protocol can be overridden by the new annotation.

TLS-/SSL-related parameters do not influence the behavior.

**Comment by timoreimann** [comment] 2019-01-06 01:16
Overall, it looks to me like everything left to do is release the new feature? What do folks think?

**Comment by aslafy-z** [comment] 2019-01-25 16:13
I'd love to see `v0.1.9` land to fix this, I'm using managed Kubernetes by DigitalOcean.

My `nginx-ingress` has its logs scrambled with failed SSL handshakes, kind of cryptic error as I haven't been able to find these local IPs on my cluster (should be the LB). It looks like that:

```
nginx-ingress-controller-d466ff77f-xmb4d nginx-ingress-controller 2019/01/25 16:09:00 [crit] 364#364: *5232 SSL_do_handshake() failed (SSL: error:1408F0C6:SSL routines:ssl3_get_record:packet length too long) while SSL handshaking, client: 10.244.15.1, server: 0.0.0.0:443
nginx-ingress-controller-d466ff77f-xmb4d nginx-ingress-controller 10.244.76.0 - [10.244.76.0] - - [25/Jan/2019:16:08:58 +0000] "<J" 400 157 "-" "-" 0 0.139 [] - - - - f8b81437ee09e22c7d792abfa63442a4
nginx-ingress-controller-d466ff77f-xmb4d nginx-ingress-controller 10.244.76.0 - [10.244.76.0] - - [25/Jan/2019:16:08:58 +0000] "S.\x03\xD3\xC19NKB\xA8\xADaH\xDF\xB8e\x8E\x16\xC9\xD9e\xD7SP\x14\xF9\x95\xAA\xD3\xDC\xE0\x8B\x88\x17z\xBC\xCAsH\x01+\xD6\xD15\x09i\x05\x0B\xFE\x01S\x01\xB3\xED\xFCc\xDA\xDE\x1D[\x13\x8E\xFF\xCE\xA9}\x1C\x7F\x01\xE6\xE0\xC3'\xBFc\xD9" 400 157 "-" "-" 0 0.652 [] - - - - 3c5b1242f4653c00f0fc8ba78288e37b
nginx-ingress-controller-d466ff77f-xmb4d nginx-ingress-controller 10.244.15.1 - [10.244.15.1] - - [25/Jan/2019:16:08:58 +0000] "i\xA4\xAC\x03z\x07\xD9\xFF\xFB\xE4\xBC;[d\xA2p\xB2\x8A\x94\x15\xE2\xDC\xF2\xB0v^e!\x80\xCA\x93\xB6\xBCq[C\xD5=\xADX\xA9\x84\x16\xFAh9T\xE8\x01\x8D\x06\x92\xB3\xCBd\x07V\xB2\xEA\xDC}|'\xB8\x93o\xAD\x99t\x02\xA6`\xCB\x11\xE6\x16\xA7\x1CWv\xEAk\xB6,\xFB\x9COu\xD7\x1B\x0BSp~\xC5\xB9\x8D\x1A\xB1\xFEV\xB4E\xF3c\xDB:\x9B\xDC}W\x82E\xEA\xB4\x13\x92\x03\xAFU\x0C\x83\xDA\xB7\xFC\xCE\xD8\x88F\xEC_\xA6\x82\xA6\xD4\xA5\xF1\xF3<p'\x03>\x05\xAB'?\x05\xC7\x90\x05I\xA0zJmer\xB02\xAE9\x04tm-!c\xAD\xC1\xE0\xFC\x90h\x9A|\x0B\xF6'\xA3\xEF\x83\x05\x22\x02L\xD6Iq\xBD\x03\xAF\x1Dw" 400 157 "-" "-" 0 0.130 [] - - - - bd6b71aeda9172d1749543a61b2ce5bb
nginx-ingress-controller-d466ff77f-xmb4d nginx-ingress-controller 10.244.15.1 - [10.244.15.1] - - [25/Jan/2019:16:08:58 +0000] "\x5CB\xFFQ\xEE\xE4\xABV\x8D\xBEE" 400 157 "-" "-" 0 1.540 [] - - - - 3a8fcd62e0ec36c5d39c35e042cfdfe7
nginx-ingress-controller-d466ff77f-xmb4d nginx-ingress-controller 10.244.15.1 - [10.244.15.1] - - [25/Jan/2019:16:08:59 +0000] "CC\x8C|" 400 157 "-" "-" 0 0.131 [] - - - - 4ded214ace50980b6b06773ba8ab302e
nginx-ingress-controller-d466ff77f-xmb4d nginx-ingress-controller 10.244.76.0 - [10.244.76.0] - - [25/Jan/2019:16:08:59 +0000] "\x0Fa\xBA\xACI\xF2rd\xCFU\xD4\x1C\xC6\x84\xF1\xB6\xA4D]\xC7B}\x97\x1F\xF4\xDF\x97\x8Bb<^\xAD+I\xDE$\xCE\xE78\x97`\x08x\xE3j2zf\x97m\x8D\xDE\xF5\xC5\xA4v\xC9\x9F\xDD\x8EzMk\x168\xDD\x8EXMAq\x00|\x95?\x95=\xF8s\xE1\x99\x9A\xB8\xEA`" 400 157 "-" "-" 0 0.112 [] - - - - 5f598064b1f073f8d6a70fb5690457a8
nginx-ingress-controller-d466ff77f-xmb4d nginx-ingress-controller 10.244.76.0 - [10.244.76.0] - - [25/Jan/2019:16:08:59 +0000] "\x1C\x9C\x18f{<\x0B\x00H\x91\x15Q\x9C\xE1\xB0.F>[p\xF7\x1E\x8A\x83\xDF\xE1{\xBC^\xEE\xF6\x89.\xDC\x079@\xB0?<*G\xE2\xF3S;\xFC\xB5\xC9\xC5 \xADl7)\x9DD\xFC\xAD\xF8\xC9\x07f\xCFr\xE6\x8B\xC0\x89\xE0D\xF8\x14{,\xD31_\xBA\xFE\xAD;\xE5\xFB\x93\xBC\xA0\x82\x01\x1277\x94[\x08N,\x9E;\xCA\xA2>\x12s*\xF9%<9!n\xE0\xED \xACj\xAF\x10\x8E[^(Jc\x93\x12@\x06\x8Ag\x06\x84-\x84\xA8\xF3\xB9\x91\xE2\x10{\x22\x1B\x19\xF5,\xF6\x92\x8D\x95\xC2B\x8Dax\xE9\x0FWJ\x1F\x88\xF0D\x93\xFB?e#(\x81\x16\x1F\xA4\xA7-4\xB5^\x1EX\xEFBL~A8\xEE\x00\x86\xD7z\xC8w\x95\xA7,^%\x19\xC2\x12\xEEQ;E\xE7\xF5\xFF4\x9C\x85\x9B\x1F\xD0\xC1\xF5;0Q\xD5\xC3\x93:\x1F@\xFB~VM9\x037\x11\xAF\x9F\x06m7\xB0~\xBD\xE7\xE7\x94W\xEF\xC3\x98\xD6\xA8R\xA8\xE5g!\xC1\x08{\x04?s\xF1\xD6\xC5W\xCB\xA7a\x9F\xEBc`GV|:^\x89\xB2k\xFA\x10\x97$\xF8K\xB9\x0BXQ\xD0\xA9\x02T\xFF\x05\xE9\xC6F\x04._\x8D\xCF\xA3yD\xDF\xB9\x04\xB4\xAFc\x02\xF31\xB5\xA9]\x8D,\x13L\x112\xD9\xE5\x83\x04/\xFB1\xFFT\xEF\xB6\x18z1q\x0C\x97_#\xA8R\x0F\x8A\x80\xD3\xEEo\xED\xA3\x8FL\x04.\xA2E{*z\xC6\xFA\xB6Z\x0Bg\x11[\xE8\x91u?\xA2\xF0\xD4\xBB\xA9\x84\xFD\x0Ew\x16\xBE\xB1\x93$\xE2\xDB\xE7" 400 157 "-" "-" 0 0.095 [] - - - - 0274b17667b81092a8d60565ca849340
nginx-ingress-controller-d466ff77f-xmb4d nginx-ingress-controller 10.244.15.1 - [10.244.15.1] - - [25/Jan/2019:16:08:59 +0000] "\x1E>\xEB\xEC>9/\xF40b\x1D\xA4\x22 \xB5\x15\xED\x1C\xF6L\xD7\xAF\x92\xCF\xCD\xFFl\xFB\xB4\x8C\x9F\xCF4D\xF9\xC7\xCF \xE9\x83\xBC\xC9]\x8C\xC2\xB01\xAF\xCF\x13\xF8snj\x0B'\xF3\x01\xDD\xB3N\xF9\xA5\xAFA\xB8\xFAL?!\xBD\x8C\x9A\x12\xA9\xF3u\x09/\xD2\xBA\x05\xB7\xB4\x0F\xC7\xFC\x8A\xCB\xF0\xFF\x80\x88\x97\xD9\xA8i\xD4\xE6n\xDE&\xA1\x08\xC9[\x03\xF6B~\xF5D\x17\x10\xEEE\xDC\x9C}\xD1<\xA1\xD7\x02\xBB\x8E\xEF\x89\xB4\xD9\xE9\x805\x07\x8Ah\x84\xB6\x0CW\xBE+7c\xE7V\x0B\x06r4D\xCC\xB7\xC0u\x97\xCE;\xADU\x0EH\xAB\x85*=,\xA3\x0E5\x8E\xE2v\xD1\xD3l\xEB\x8F\xC7z[\xD4]b\xBAY" 400 157 "-" "-" 0 1.084 [] - - - - 1a40a4aabe584160646028b2c68bbbd8
nginx-ingress-controller-d466ff77f-xmb4d nginx-ingress-controller 10.244.15.1 - [10.244.15.1] - - [25/Jan/2019:16:08:59 +0000] "!\xD6$8\x07\x1D\xB8\x8ErG\xB7v&\x02\xFF\xA9w#\x82?\x8A\x90\x18\xF3\xB5\x18\x1Dyv\x1Fz\x96\xC9-\x10\x92N\x5C\xE5\xEE{\x9AB\x90\xC8\xB5B%\xFE\xF1\x047\xF7\x82^\xED\xBB5,\xE2\xBC\x82-\xDE\xF3\xC1\xE8\xBDSs\xAA\x89V\x88\xA0\xCA\xF9\xCC'F\xDE:g\xE5\x1F\xA5\x8F\x05\xAF\xF7\xE3,\xEE\x1F\x10\xA1\x8B\x06\xEC^&\xC9fI\x08R\x1C\xA1\xD1JtO\x0B(C\x01\x84\x9A\x8A\x84S\xDF\x9DU1\xC9\xC2a^2\x1F\xD7\xB8)\xD0b\x1C{~N]jr\xF6\xA1\xD3&F\xAF\x83^\xDE\xEF\xBF\xCC\xE2<\xA1\x0C\x06\xEBH\xBA\x9C\xE3\x9B$\x8D\xEFb\xBAbq{J:\xCBX\xE5\x1C\x22\xBFQ" 400 157 "-" "-" 0 0.159 [] - - - - a1c42c06489ceae4ffc7943bca3e6796
nginx-ingress-controller-d466ff77f-xmb4d nginx-ingress-controller 10.244.15.1 - [10.244.15.1] - - [25/Jan/2019:16:08:59 +0000] "\x15\xEFi{C\x99\xC4\x8C)\xD6\x9C\x802\xE1\xBB\xB7\x96\xF6\xCBh\x93@\x85\x97\xDE&\x9D\xB8\xEF\x00\x99|\x09B\x9E\xDD\xFDO\xA8\xE5k\x9Cb\x1B\x93\x10\x80\xEF(\x03R\x03\xBA@<\xE8v\xA7\xAA\xA7\x06d/\xB4\x1B\x1C\xA0\x0F%\x09bz=`\xA9\xA4\xDA}\xA1U\x82\x08\x169h\x92\xAF)\x05\x9COfC\x89IH>\x19\xC2\xE3\xC3'\xD7\xECS\xED\xE2\xB1\xECr(\xD4\xA4\x12\xCC" 400 157 "-" "-" 0 0.279 [] - - - - a4479c3bf145feaafc646689259cbb3e
nginx-ingress-controller-d466ff77f-xmb4d nginx-ingress-controller 10.244.15.1 - [10.244.15.1] - - [25/Jan/2019:16:09:00 +0000] "?\x0B\xE7\x11\x80^ra(\xFD=\xD9n\x12\xED\xDD\x04-:G\xB2s\xCDc3\xFA\x82\x97^\x0EHJ\x04\xD6\xC04\x98,\xB3(dc\x9B\xCB\xFF\x0C$\x18\xFE\x8FX\xEB}j\xF04w\x18\xCC\x8A3\xFB\x85jS\x84\xE5\xDA\x9AV%\x85\xEB\x7F\xD1\x09Be\x09=\xBB\xB3#D\x108\xEAZ\xD61\xA2\xC0\xF4\xE8s\xAF\xD6\xEB\x83\xDA\xC2\x96-\xBB\xCF\x1C\x17\xD7\xC8j\x89\xEFe\x07~8\x84$\x19j\xB1\x1COQ\x93\xB9n\xB2\xAC\xB9\xC9\xBE8\xA6^hyG\x14Q\x0Fe\xCD?\xB6\xBB\xBEEZ\xD8\xF5\x99\xD3\xD77\x02\xD7\xE5\xAC9=(Rw\xB39a\x81p\x84\x07m" 400 157 "-" "-" 0 0.154 [] - - - - 92f522caee6fc45f840114b82a3b0b6f
nginx-ingress-controller-d466ff77f-xmb4d nginx-ingress-controller 2019/01/25 16:09:00 [crit] 364#364: *5232 SSL_do_handshake() failed (SSL: error:1408F0C6:SSL routines:ssl3_get_record:packet length too long) while SSL handshaking, client: 10.244.15.1, server: 0.0.0.0:443

...
```

**Comment by timoreimann** [comment] 2019-02-08 05:27
I'll look into moving forward with a release.

**Comment by daimoniac** [comment] 2019-02-13 06:16
Loadbalancer creation fails:

```
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "tcp"
    service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "true"
```

```
$ kubectl get svc ambassador
  Warning  CreatingLoadBalancerFailed  7s                  service-controller  (combined from similar events): Error creating load balancer (will retry): failed to ensure load balancer for service bst2-prod/ambassador: POST https://api.digitalocean.com/v2/load_balancers: 422 (request "6070ec6c-e674-4c0e-b14e-6fe5e18a2d39") health check only supports TCP and HTTP
```

**Comment by daimoniac** [comment] 2019-02-13 06:22
It even happens when `do-loadbalancer-healthcheck-protocol` is not set.

```
                          service.beta.kubernetes.io/do-loadbalancer-algorithm: round_robin
                          service.beta.kubernetes.io/do-loadbalancer-protocol: https
                          service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: true
                          service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: true
                          service.beta.kubernetes.io/do-loadbalancer-tls-ports: 443
```

```
kubectl get svc ambassador
  Warning  CreatingLoadBalancerFailed  7s                  service-controller  (combined from similar events): Error creating load balancer (will retry): failed to ensure load balancer for service bst2-prod/ambassador: POST https://api.digitalocean.com/v2/load_balancers: 422 (request "6070ec6c-e674-4c0e-b14e-6fe5e18a2d39") health check only supports TCP and HTTP
```

It seems that `do-loadbalancer-healthcheck-protocol` is ignored and the value of `do-loadbalancer-protocol` is used for the health check. In my case, that is `https`, which is illegal for healthcheck.

**Comment by aslafy-z** [comment] 2019-02-13 11:27
@daimoniac which CCM version are you using? see https://github.com/digitalocean/digitalocean-cloud-controller-manager/issues/158#issuecomment-451705835
`do-loadbalancer-healthcheck-protocol` haven't been released yet.

@timoreimann Any chance it lands this week? Thanks

**Comment by timoreimann** [comment] 2019-02-13 11:33
@aslafy-z I'm actively working on getting this PR merged and cutting a release by the end of the week. Keep your fingers crossed. 🤞

**Comment by acejam** [comment] 2019-02-13 23:28
+1 for a new release

**Comment by timoreimann** [comment] 2019-02-27 09:51
CCM v0.1.10 has been rolled out (v0.1.9 contained a bug, please don't use it) and should be available on all DO images. Until cluster upgrades are possible, creating a new cluster should pull in the right CCM version.

**Closed by timoreimann** 2019-02-27 09:51 UTC
